version = 1

[[annotations]]
path = [
    "src/*.py",
    "src/*.ipynb",
    "build.rb",
    "slider.lua",
    "assets/after_body.html",
    "assets/custom_header.html",
    "assets/custom.css",
    "assets/helpers.css",
    "assets/nord_helpers.css",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
    "figures/*.png",
    "figures/*.svg",
    "assets/*.drawio.svg",
    "assets/qr_code_*.png",
    "README.md",
    "data/**/README.md",
    "data/map.geojson",
    "data/yjmob100k/activity.csv",
    "data/yjmob100k/unique_users.csv",
    "data/yjmob100k/daily_activity_*.csv",
    "data/yjmob100k/port_messe_nagoya_activity.csv",
    "data/yjmob100k/grid_bl_2449.geojson",
    "data/threshold.csv",
    "slides.md",
    "test_slider.md",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "data/yj100kmob/activity.csv",
    "data/yj100kmob/unique_users.csv",
    "data/yj100kmob/grid_bl_2449.geojson",
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Gergő Pintér"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["data/geojson/*", "data/boundary.geojson"]
precedence = "override"
SPDX-FileCopyrightText = "OpenStreetMap contributors"
SPDX-License-Identifier = "ODbL-1.0"

[[annotations]]
path = "figures/**/*"
precedence = "override"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "**/.gitignore",
    "src/plotting_config.toml",
    "pyproject.toml",
    "uv.lock",
    ".python-version",
    "references.bib",
    "build_config.yaml",
    ".github/workflows/main.yaml",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 Gergő Pintér"
SPDX-License-Identifier = "0BSD"


[[annotations]]
path = ["assets/reveal.js-*/**/*"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2011-2024 Hakim El Hattab, http://hakim.se, and reveal.js contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["assets/BeerSlider.css", "assets/BeerSlider.js"]
precedence = "override"
SPDX-FileCopyrightText = "2018 PeHaa Hetman"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["assets/fontawesome/webfonts/*"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Fonticons, Inc. (https://fontawesome.com)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["assets/fontawesome/css/*.css"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Fonticons, Inc."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "data/weeplace/budapest.geojson"
precedence = "override"
SPDX-FileCopyrightText = "Zexun Chen, Sean Kelty, Alexandre G. Evsukoff, Brooke Foucault Welles, James Bagrow, Ronaldo Menezes & Gourab Ghoshal"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "data/yjmob100k/yjmob100k-dataset1_sample.csv"
precedence = "override"
SPDX-FileCopyrightText = "Yabe, T., Tsubouchi, K., Shimizu, T., Sekimoto, Y., Sezaki, K., Moro, E., & Pentland, A. (2024)."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "assets/nord.css"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2016-present Sven Greb <development@svengreb.de>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["figures/nasa.jpg", "figures/nasa.tif"]
precedence = "override"
SPDX-FileCopyrightText = "NASA’s Earth Observatory"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["assets/*.csl"]
precedence = "override"
SPDX-FileCopyrightText = "CSL project (https://citationstyles.org)"
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = ["assets/CC-BY.svg"]
precedence = "override"
SPDX-FileCopyrightText = "Creative Commons"
SPDX-License-Identifier = "CC-BY-SA-4.0"
